import {
  Users,
  Building2,
  HardHat,
  UserCog,
  Truck,
  ClipboardList,
  GitBranch,
  FolderKanban,
  Calculator,
  Wrench,
  Banknote,
  UserCheck,
  ClipboardCheck,
  Trash2,
  LayoutDashboard,
  History,
  Settings,
} from 'lucide-react'

export const NAV_ITEMS = [
  {
    id: 'dashboard',
    label: 'İdarə Paneli',
    path: '/',
    icon: LayoutDashboard,
  },
  {
    id: 'customers',
    label: 'Müştərilər',
    path: '/customers',
    icon: Building2,
    module: 'CUSTOMER_MANAGEMENT',
  },
  {
    id: 'contractors',
    label: 'Podratçılar',
    path: '/contractors',
    icon: HardHat,
    module: 'CONTRACTOR_MANAGEMENT',
  },
  {
    id: 'investors',
    label: 'İnvestorlar',
    path: '/investors',
    icon: Banknote,
    module: 'INVESTORS',
  },
  {
    id: 'operators',
    label: 'Operatorlar',
    path: '/operators',
    icon: UserCheck,
    module: 'OPERATORS',
  },
  {
    id: 'users',
    label: 'İstifadəçilər',
    path: '/users',
    icon: Users,
    module: 'EMPLOYEE_MANAGEMENT',
  },
  {
    id: 'roles',
    label: 'İstifadəçi və rol',
    path: '/roles',
    icon: UserCog,
    module: 'ROLE_PERMISSION',
  },
  {
    id: 'garage',
    label: 'Qaraj',
    path: '/garage',
    icon: Truck,
    module: 'GARAGE',
  },
  {
    id: 'requests',
    label: 'Sorğular',
    path: '/requests',
    icon: ClipboardList,
    module: 'REQUESTS',
  },
  {
    id: 'coordinator',
    label: 'Koordinator',
    path: '/coordinator',
    icon: GitBranch,
    module: 'COORDINATOR',
  },
  {
    id: 'projects',
    label: 'Layihələr',
    path: '/projects',
    icon: FolderKanban,
    module: 'PROJECTS',
  },
  {
    id: 'accounting',
    label: 'Mühasibatlıq',
    path: '/accounting',
    icon: Calculator,
    module: 'ACCOUNTING',
  },
  {
    id: 'service',
    label: 'Texniki Servis',
    path: '/service',
    icon: Wrench,
    module: 'SERVICE_MANAGEMENT',
  },
  {
    id: 'approval',
    label: 'Təsdiq Növbəsi',
    path: '/approval',
    icon: ClipboardCheck,
    module: 'OPERATIONS_APPROVAL',
  },
  {
    id: 'trash',
    label: 'Silinmiş Məlumatlar',
    path: '/trash',
    icon: Trash2,
    module: 'TRASH',
  },
  {
    id: 'config',
    label: 'Konfiqurasiya',
    path: '/config',
    icon: Settings,
    module: 'CONFIG',
  },
  {
    id: 'audit',
    label: 'Audit',
    path: '/audit',
    icon: History,
    module: 'AUDIT_LOG',
  },
]
