import {
  Users,
  Building2,
  HardHat,
  UserCog,
  Truck,
  ClipboardList,
  GitBranch,
  FolderKanban,
  Calculator,
  Wrench,
} from 'lucide-react'

export const NAV_ITEMS = [
  {
    id: 'customers',
    label: 'Müştərilər',
    path: '/customers',
    icon: Building2,
    module: 'CUSTOMER_MANAGEMENT',
  },
  {
    id: 'contractors',
    label: 'Podratçılar',
    path: '/contractors',
    icon: HardHat,
    module: 'CONTRACTOR_MANAGEMENT',
  },
  {
    id: 'users',
    label: 'İstifadəçilər',
    path: '/users',
    icon: Users,
    module: 'EMPLOYEE_MANAGEMENT',
  },
  {
    id: 'roles',
    label: 'İstifadəçi və rol',
    path: '/roles',
    icon: UserCog,
    module: 'ROLE_PERMISSION',
  },
  {
    id: 'garage',
    label: 'Qaraj',
    path: '/garage',
    icon: Truck,
    module: 'GARAGE',
  },
  {
    id: 'requests',
    label: 'Sorğular',
    path: '/requests',
    icon: ClipboardList,
    module: 'REQUESTS',
  },
  {
    id: 'coordinator',
    label: 'Koordinator',
    path: '/coordinator',
    icon: GitBranch,
    module: 'COORDINATOR',
  },
  {
    id: 'projects',
    label: 'Layihələr',
    path: '/projects',
    icon: FolderKanban,
    module: 'PROJECTS',
  },
  {
    id: 'accounting',
    label: 'Mühasibatlıq',
    path: '/accounting',
    icon: Calculator,
    module: 'ACCOUNTING',
  },
  {
    id: 'service',
    label: 'Texniki Servis',
    path: '/service',
    icon: Wrench,
    module: 'SERVICE_MANAGEMENT',
  },
]
