name: Deploy Frontend

on:
  push:
    branches: ["*"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER2_SSH_HOST }}
          username: ${{ secrets.SERVER2_SSH_USER }}
          key: ${{ secrets.SERVER2_FRONTEND_KEY }}
          script: |
            cd /opt/cesapp
            git -C frontend pull
            docker compose up -d --build frontend
            echo "Frontend deploy tamamlandı!"
